src/components/Chat/Chat.js, src/data/graphql/Database/chat/GetChatLines.js
Bottom to top order is quite unintuitive to read.
=> fix(battle): show battle chat log in top to bottom order

src/components/Recplayer/Recplayer.js
https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState
=> Auto play recs if visible

package.json, src/components/BattleList/BattleList.js, src/components/BattleList/battlelist.css, src/components/BattleList/battles.graphql, src/components/Chat/Chat.css, src/components/Kuski/Kuski.js, src/components/Kuski/package.json, src/components/Layout/Layout.css, src/data/graphql/Database/battle/GetBattles.js, src/data/graphql/Database/battle/GetBattletime.js, src/data/graphql/Database/chat/GetChatLines.js, src/routes/battle/Battle.css, src/routes/battle/Battle.js, src/routes/battle/battle.graphql, src/routes/kuski/Kuski.css, src/routes/kuski/Kuski.js, src/routes/kuski/PlayedBattles.css, src/routes/kuski/PlayedBattles.js, src/routes/kuski/battles.graphql, src/routes/kuskis/Kuskis.css, src/routes/kuskis/Kuskis.js, yarn.lock
Display battle leader history. This is displayed only for normal battles at the moment, but maybe it could be somehow extended to other battle types too.
=> feat(battle): show battle leader history

src/data/graphql/Database/battle/GetBattles.js, src/routes/level/Level.js, src/routes/level/level.graphql, src/routes/replay/Replay.css, src/routes/replay/Replay.js
Added an expandable list of battles for the level on the level page, and a link to level page on the replay page.
=> feat(level): list of battles for the level

src/components/BattleList/BattleList.js
Previous merge resulted in a conflict that I messed up a bit. This resolves that issue, while also fixing the nested ternary error.
Probably not the most elegant solution - suggestions/fixes welcome.
=> refactor(battlelist): fixed nested ternary error

src/components/RecList/RecList.js, src/components/RecListItem/RecListItem.js, src/routes/replay/Replay.js
Highlight current replay in list of other replays in level.
https://github.com/elmadev/elmaonline-site/issues/112
=> feat(replay): highlight selected replay

src/components/SearchBar/SearchBar.css, src/components/SearchBar/SearchBar.js, src/components/SearchBar/package.json, src/components/TopBar/TopBar.js, src/data/graphql/Database/schema.js, src/data/graphql/Database/search/Search.js, src/pages/search/Search.css, src/pages/search/Search.js, src/pages/search/index.js, src/router.js
=> feat(site): search levels and replays by filename

src/utils/discord/battleNotifier/bnCommand/bnCommand.js, src/utils/discord/battleNotifier/bnCommand/messageUtils/readUserMessage.js, src/utils/discord/battleNotifier/bnCommand/subCommands/setBn.js, src/utils/discord/battleNotifier/bnCommand/subCommands/testBn.js, src/utils/discord/battleNotifier/bnCommand/subCommands/toggleBn.js, src/utils/discord/discord.js, src/utils/discord/logger.js
Added logs for battle notifier command. Logs files for path `./bn/[yyyy-mm-dd].log`.
Currently only logging the errors catched at battle notifier, with error message and stack. This could help finding out why Bene can't use the bot :)
Also did a few quick fixes:
- Typo at setBn message.
- Changed to 5 minutes to respond and improved the timeout message.
- Removed the reaction icon from `!bn on/off` and added an explanatory message reply instead.
=> refactor: 💡 Add bn logs to help with error finding

src/api/cups.js, src/pages/cup/Team.js, src/pages/cup/store.js
- persist teamOptions to localStorage
=> feat(cups): add option to show ongoing event team recs

src/components/Upload/Upload.js
=> fix(Upload): process error object properly

src/data/graphql/Database/chat/GetChatLines.js
=> fix(Chat): increase battle chat log line limit to 2048

package.json, src/api/chat.js, src/components/ChatView/ChatView.js, src/components/ChatView/store.js, src/pages/chat/Chat.js, yarn.lock
Fixes #295 
For improving Kuski autocomplete performance I dragged in this example https://material-ui.com/components/autocomplete/#virtualization
If other places could use this I could clean it up and make it reusable.
Will also have to refactor Chat page file which has too much stuff atm.
For performance `Count` checkbox is unchecked by default which means I have to set a big number (9999999 now) as line count or pagination won't work.
=> Fix chat log page problems

src/pages/levelpack/LevelPack.js
fixed a buggy dropdown in the levelpack settings by making it a radio button instead, refactored css to styled-components
=> fix(levelpacks): fix bug by changing functionality, refactor

src/components/Link/Link.js, src/pages/battle/Battle.js, src/pages/battles/Battles.js
=> refactor(other): convert to function components :bear:

package.json, src/api/level.js, src/components/BattleCard/BattleCard.js, src/components/BattleCard/battleCard.css, src/components/LevelMap/LevelMap.js, src/components/LevelMap/package.json, src/components/LevelMap/store.js, src/data/api.js, src/store/easypeasy.js, yarn.lock
=> Add LevelMap

package.json, src/api/index.js, src/api/news.js, src/components/News/News.js, src/components/News/package.json, src/components/News/store.js, src/data/api.js, src/data/models/News.js, src/data/models/index.js, src/pages/home/Home.js, src/store/easypeasy.js, yarn.lock
=> feat(home): add news feed

package.json, src/pages/kuski/Kuski.js, src/server.js, src/utils/download.js, yarn.lock
=> feat(kuskis): kuski shirt endpoint

src/api/battle.js
=> add recfilename to BattlesBetween attributes

package.json, src/api/index.js, src/api/upload.js, src/constants/lists.js, src/data/models/Upload.js, src/data/models/index.js, src/server.js, src/utils/auth.js, src/utils/upload.js, yarn.lock
=> feat(other): file upload

src/api/levelpack.js
=> feat(levelpacks): allow mods to admin all packs

src/api/battle.js
=> fix(battles): hide unstarted aborted

src/api/allfinished.js, src/api/besttime.js, src/api/replay.js, src/data/models/BestMultitime.js
I have also filled in the missing Driven data in the db (for both single and multi).
=> Return Driven for best times, block times for locked levs more consistently

package.json, src/api/levelpack.js, src/utils/middleware.js, yarn.lock
client: https://github.com/elmadev/elmaonline-web/pull/43
=> feat(levelpack): add update levelpack endpoint

src/api/cups.js, src/api/levelpack.js
from ~3000ms to ~80ms for internals :)
=> refactor(levelpacks): tt calc optimization

src/api/allfinished.js, src/api/besttime.js, src/api/index.js, src/api/notification.js, src/api/replay_comment.js, src/data/models/Notification.js, src/data/models/index.js, src/server.js, src/utils/events.js, src/utils/notifications.js
- notify replay uploader when there's a new comment
- notify previous record holder when there's new best time
=> feat(notifications): add notifications

src/config.js, src/server.js, src/utils/database.js
console log endpoint and queries, both with options in config and off by default. I always develop with consoleEndpoints true (maybe we should default it to true (if not in production)). Gives you an idea of performance without cluttering your console too much.
=> feat(dev): console endpoints/queries

src/api/replay_comment.js, src/data/models/index.js
backend for: https://github.com/elmadev/elmaonline-web/pull/66
=> feat(replayComments): get all

src/api/allfinished.js, src/api/crippled.js, src/api/index.js
https://github.com/elmadev/elmaonline-site/issues/462
=> feat(allfinished): crippled

src/api/battle.js
=> feat(battles): latest X battles endpoint

src/api/replay.js
Fixes https://github.com/elmadev/elmaonline-site/issues/487
=> feat(replays): filter replays by level pack

src/api/battle.js, src/utils/database.js
For this: https://github.com/elmadev/elmaonline-web/pull/113
It's a bit less changes than it looks like as I removed /* eslint-disable prettier/prettier */ as first line, so it re-formatted some stuff. Hoping it wasn't there for some specific reason.
=> feat(battles): advanced search

src/api/levelpack.js
Add record count to king list in level packs, backend edition
Closes: 572
=> feat(levelpacks): add record count for levelpack kinglist fetch

src/api/cups.js
I didnt test this. hope i wrote it in the right spot.
=> feat(ongoing-cups): return level.Hidden for ongoing events

src/api/levelpack.js
back-end for here: https://github.com/elmadev/elmaonline-web/pull/148
=> Levelpack record history

src/api/replay_comment.js
Server changes for client PR: https://github.com/elmadev/elmaonline-web/pull/154
=> feat(replay-comments): add pagination

src/api/replay.js
Comment and Unlisted can still only be edited by the uploader.
=> feat(replays): Allow mods to edit replay tags and DrivenBy

src/api/cups.js
https://github.com/elmadev/elmaonline-web/pull/253
=> feat(cup): get by level

src/api/allfinished.js
Part of https://github.com/elmadev/elmaonline-site/issues/711
=> feat(levels): include time file data in personal leader history

src/api/level.js
-  80% of the feature done by chatgpt, I helped a bit with arrow shapes etc.
Closes https://github.com/elmadev/elmaonline-site/issues/744
=> feat(levels): add arrows to level png
