elmadev/elmaonline-site

- src/server.js
This fixes the bug where material ui css would disappear after the first page load in _production_ mode. I'm not exactly sure what's the root cause of the problem, but if anyone wants to take a look at it here's something to consider when tracking: if you set webpack clientConf [NODE_ENV](https://github.com/elmadev/elmaonline-site/blob/890047e2aa1d12f401a5b4973412567e57e8de71/tools/webpack.config.js#L322) to fixed value "development" the bug disappears in production, so it seems to have something to do specifically with creating the client bundle in production mode. I couldn't find any places where it would affect our code so maybe it's dependant on some external library or something.
Anyways, this circumvents the bug but isn't fixing the real problem.
> fix(site): persist material ui css on first render

- package.json
- src/components/BattleList/BattleList.js
- src/components/BattleList/battles.graphql
- src/components/Layout/Layout.css
- src/components/SideBar/SideBar.css
- src/components/Time/Time.js
- src/components/variables.css
- src/data/graphql/Database/battle/GetBattles.js
- src/routes/battle/Battle.js
- src/routes/battle/battle.graphql
- src/routes/kuski/Kuski.js
- src/routes/kuski/PlayedBattles.js
- src/routes/kuski/battles.graphql
- src/routes/level/Level.js
- src/utils.js
- yarn.lock
Sorting results work for some battle types, but probably not for certain special types such as flag tag, speed and finish count; those still need to be _sorted out_. Also the result display logic needs some work on those battle types. Apple results should be displayed correctly.
Also the pagination of battles on kuski page is included, though a separate pagination component should be created instead of using the terrible mui one which does not allow user to jump to a certain page directly.
> Results fixes and battle pagination

- src/components/BattleList/BattleList.js
- src/data/graphql/Database/battle/GetBattles.js
- src/routes/home/Home.js
Queued and aborted battles have "Queued" or "Aborted" displayed in the Winner column.
> fix(battlelist): fix display of queued and aborted battles

- .eslintrc.js
- package.json
- src/components/RecList/RecList.js
- src/routes/level/Level.js
- src/routes/replay/Replay.js
Store filters into query params.
Fixes https://github.com/elmadev/elmaonline-site/issues/110
> Fix remembering filters when navigating to a different rec in the same level

- src/components/BattleList/BattleList.js
- src/data/graphql/Database/battle/GetBattles.js
- src/data/graphql/Database/battle/GetBattletime.js
- src/routes/battle/Battle.css
- src/routes/battle/Battle.js
- src/routes/battle/battle.graphql
- src/routes/home/Home.js
- src/routes/home/home.graphql
- src/routes/level/Level.css
- src/routes/level/Level.js
- src/routes/level/level.graphql
- src/utils.js
Battle and level pages are now visible, but with limited content, as per #88. Highlighting of the three types of battles was refactored to be neater and more flexible; background colour is defined in a utils.js function now.
Outstanding issue: some sensitive battle data is being leaked with overly broad db queries. Some were added/expanded by me, but I think some were also leaky before. I'll go through the queries tomorrow and try to refactor them so that only safe data is pulled.
**Please do not push to elma.online before the above is confirmed.**
It would be useful to test it on test.elma.online though, together with other fixes.
------------------------------------------------------------------------------
**Update:**
fixed/updated display of Kuskis in battle tables on the home page …
> feat(site): limited display of queued, ongoing and aborted battles

- src/data/graphql/Database/time/GetTimes.js
- src/pages/levelpack/LevelPack.css
- src/pages/levelpack/LevelPack.js
Display the best time in level pack level listing.
Additionally this PR fixes the bug when selecting the same level on the levpack level list several times it would show less and less of top10 times each time. Also introduces possibility to define how many best times are queried from the db for the selected level.
> feat(levelpack): display best time in level pack level listing

- .gitignore
- src/config.js
- src/utils/discord/battleNotifier/bnStore/bnStore.js
- src/utils/discord/battleNotifier/bnStore/jsonFs.js
- src/utils/discord/discord.js
- src/utils/discord/fileUtils.js
- src/utils/discord/logger.js
Updated the discord Logger so it now retains a path defined at the config file instead of a hardcoded string internally.
`bnStore.js` already received it's file path at initialization.
For the logger and bnStore added a new line at initialization that creates the storage folder if it doesn't already exists, using the initialization path.
Both paths are defined at the config file like:
```json
bnStorePath: '../bn/bn.store.json',
bnLogsPath: '../bn/logs/',
```
If it's not a production environment it will just use a `./bn/` folder for both store and logs, that will be ignored by `.gitignore`.
> refactor: 💡 Store bn store and logs outside builds reach

- package.json
- yarn.lock
Fix importing external css modules into javascript.
> fix: 🐛 Upgrade webpack-node-externals fixes webpack usage

- src/pages/cup/Events.js
Lifted up the condition for coloring links from `EventLink` to `EventContainer` so it also takes effect for `Kuski` inner links.
When the `Event` is highlighted the background color turns green but the `Kuski` inner link kept green instead of turning white, so it vanished :D
1. Go to a Cup.
2. Go to the Events tab.
3. Select an Event.
4. The Kuski name vanished in the green background => now turns white
> style: 💄 Fix cup event link color on highlighted event

- src/components/Table/DerpTable.js
- src/pages/cup/Events.js
- src/pages/cupreplay/CupReplay.js
Fixed cup replay table sync issue. When watching a replay from an event and then visiting another replay from another event, the table below the replay used the replays from the previous visited event instead of the current one.
To fix this, added the `replay` to the `useEffect` dependency array. The `replay` changed but the `useEffect` didn't take it into account, because it was not listed as a dependency.
Other fixes: removed some warning from list of components without keys and DerpTable prop types. [Should always give unique keys when rendering an array of components](https://reactjs.org/docs/lists-and-keys.html#keys) and the DerpTable received an array of string or objects as `headers`.
1. Go to a cup (e.g. https://elma.online/cup/TTC1)
2. Go to Events tab
3. Select an Event (e.g. …
> fix(cups): fix other replays table sync issue

- src/utils/discord/battleNotifier/__tests__/notifyBattle.test.js
- src/utils/discord/battleNotifier/battleNotifier.js
- src/utils/discord/battleNotifier/notifyBattle.js
- src/utils/discord/battleNotifier/userConfig/UserConfig.js
- src/utils/discord/discord.js
Old legacy configs stored in `bnStore.json` didn't include some of the new rules like `levelPatterns` and notification code expects all configs to have all rules. 
I forgot to parse the configs coming from `store.getAll()` so that all configs are a consistent `UserConfig`.
Also added a missing top level try and catch for `battleNotifier.notifyBattle` at `discord.js`, since all async/await calls must be wrapped in try/catch at least at some top level.
Plus fixed a minor default value for `userConfig.isOn`:
```js
- const isOn = values.isOn || true; // always defaults to true.
+ const isOn = values.isOn !== undefined ? values.isOn : true;
```
> fix(other): Fix notify BN old configs without new rules

- src/utils/discord/battleNotifier/notifyBattle.js
- src/utils/discord/battleNotifier/userConfig/__tests__/userConfigParser.test.js
- src/utils/discord/battleNotifier/userConfig/index.js
- src/utils/discord/battleNotifier/userConfig/userConfigParser.js
Complex level name patterns were limited to 8 characters as if they were simple patterns. This is because did not differentiate between simple and complex level name patterns during the parsing of the user input.
- Simplex patterns (only letters, numbers and underscore) can only be between 0 and 8 chars since level names have that limit.
- Complex patterns (regular expressions) can be of any length.
> fix(other): Fix BN regexp level patterns limited to 8 chars

- src/components/LeaderHistory/LeaderHistory.js
Fix for the description of the leader time development line when 1) the first finished run is the fastest or 2) when there's only one finished run.
> fix(battles): leader time info when ff time is fastest

- src/api/index.js
- src/api/replay.js
- src/api/tag.js
- src/data/models/ReplayTags.js
- src/data/models/Tag.js
- src/data/models/index.js
- src/middlewares/requireMod.js
Table definitions from test db:
```sql
CREATE TABLE `tag` (
`TagIndex` int(11) NOT NULL AUTO_INCREMENT,
`Name` varchar(255) NOT NULL,
`Hidden` tinyint(1) NOT NULL DEFAULT '0',
PRIMARY KEY (`TagIndex`),
UNIQUE KEY `NameUniqueIndex` (`Name`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8;
```
```sql
CREATE TABLE `replay_tags` (
`ReplayIndex` int(11) NOT NULL,
`TagIndex` int(11) NOT NULL,
PRIMARY KEY (`TagIndex`,`ReplayIndex`),
KEY `ReplayIndex` (`ReplayIndex`) USING BTREE,
KEY `TagIndex` (`TagIndex`) USING BTREE,
CONSTRAINT `replay_tags_ibfk_2` FOREIGN KEY (`ReplayIndex`) REFERENCES `replay` (`ReplayIndex`),
CONSTRAINT `replay_tags_ibfk_3` FOREIGN KEY (`TagIndex`) REFERENCES `tag` (`TagIndex`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
If our `tag` table looks like this, current …
> feat(replays): add tags for replays

- src/api/player.js
- src/data/models/index.js
Adds ranking data to the all players endpoint only. Could be added to other ones but not needed at the moment.
> feat(players): back-end for new players by country page

- src/api/levelpack.js
endpoint to efficiently get internal best times and/or total times for a single kuski.
harcoded int levelpack ID.. i assume never going to change and is 84 in prod?
> feat(levelpack): int tt endpoint

- src/api/besttime.js
I think this was due to a merge conflict being resolved incorrectly. 
doesn't really need to be added to dev until the client-side stuff is ready for staging.
> fix(besttime/best-records): missing dependency

- src/api/crippled.js
Not sure if production server has a battleIndex column in the crippled table, but since it's not on dev this is causing some errors which prevents data from being shown on client.
> fix(crippled): remove unnecessary battle index column

- src/api/levelpack.js
- src/data/models/PlayStats.js
The old stats endpoint queried for records, king list and total times, which was a lot of work for the internal levelpack. So I added a new endpoint which only gets the records and uses some optimized SQL. It doesn't use the ORM since the ORM doesn't generate a very optimized query. I don't know how fast SQL vs. ORM is, but the front-end can hopefully get internal levelpack records in a few seconds now as compared to 10s or more as it was before when the endpoint was also doing the other stuff.
The old stats endpoint was not removed as its still used for most tabs in the client.
> feat(levelpack): faster query for records, and in its own endpoint

- src/api/levelpack.js
- src/utils/dataImports.js
I decided to do this in memory for now. I don't think I usually end up mutating any variables in a module like this, but I think it will work fine in production. Let me know if you think otherwise. In dev it works fine, but if you save any file, the hot-reload will cause the module to get re-initialized, so the variable will take on its default value again.
Also the reason I decided to use in memory is because I haven't used node in a while and i'm not too familiar with the file system stuff, so I thought this would be easier for now. If you prefer just let me know and i'll use a file instead. (can probably just stick it in /data/json, where the kuskiMap data is)
Note that the method of caching here prefers a fast query basically always, so it could serve stale data, but I think for now …
> feat(levelpack): cache all packs stats query (in memory for now)

- src/api/level.js
- src/api/levelpack.js
- src/api/tag.js
- src/data/models/LevelPackTags.js
- src/data/models/LevelTags.js
- src/data/models/Tag.js
- src/data/models/index.js
- Added tags for levels and levelpacks
- Created new endpoint `GET /levels` which returns list of levels filtered by given query params
> [!IMPORTANT]
> Needs the following changes to database.
- `tag`
- Add `Type`
- Change uniqueIndex from `Name` -> `Name+Type`
- `level_tags`
- Create table
- `levelpack_tags`
- Create table
- `level`
- Add index to `AddedBy`
> Improve tag system + add new level search

- src/utils/upload.js
The number linking lev and rec is two bytes earlier in Across lev header than in Elma lev header
> fix(replays): fix rec upload for Across levs

- src/api/taswr.js
Allow Kopaka to load int without levelid
> fix(other): fix casing for internal levels

- src/api/levelstats.js
- src/config.local.js
- src/data/models/LevelStats.js
Adds an endpoint to get level stats for a collection of levels...
right now just supports passing level IDs, which is good enough.
Used for 2 new pages currently: Level pack play stats tab, Cup play stats tab.
> Level collection stats
